
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lang2.parser;

/** CUP generated class containing symbol constants. */
public class Lang2ParserSym {
  /* terminals */
  public static final int CHAR_TYPE = 29;
  public static final int OPEN_PAREN = 13;
  public static final int BOOL_TYPE = 28;
  public static final int MULT = 4;
  public static final int CHAR = 50;
  public static final int NOT_EQUAL = 12;
  public static final int INT = 44;
  public static final int FOR = 39;
  public static final int MINUS = 3;
  public static final int GREATER_THAN = 34;
  public static final int DATA = 36;
  public static final int NOT = 7;
  public static final int SEMICOLON = 19;
  public static final int AND = 8;
  public static final int CLOSE_PAREN = 14;
  public static final int COMMA = 23;
  public static final int CLASS = 37;
  public static final int DIV = 5;
  public static final int VOID_TYPE = 30;
  public static final int PLUS = 2;
  public static final int ASSIGN = 11;
  public static final int IF = 31;
  public static final int ID = 46;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int AMP = 43;
  public static final int RETURN = 33;
  public static final int TRUE = 48;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int NULL = 35;
  public static final int OPEN_BRACE = 15;
  public static final int MOD = 6;
  public static final int INT_TYPE = 26;
  public static final int CLOSE_BRACKET = 18;
  public static final int OPEN_BRACKET = 17;
  public static final int TYID = 47;
  public static final int ITERATE = 21;
  public static final int ARROW = 42;
  public static final int COLON = 24;
  public static final int ELSE = 32;
  public static final int READ = 22;
  public static final int DOUBLE_COLON = 25;
  public static final int FLOAT = 45;
  public static final int INSTANCE = 38;
  public static final int CLOSE_BRACE = 16;
  public static final int FALSE = 49;
  public static final int LESS_THAN = 9;
  public static final int FLOAT_TYPE = 27;
  public static final int EQUAL_EQUAL = 10;
  public static final int PRINT = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "NOT",
  "AND",
  "LESS_THAN",
  "EQUAL_EQUAL",
  "ASSIGN",
  "NOT_EQUAL",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "SEMICOLON",
  "PRINT",
  "ITERATE",
  "READ",
  "COMMA",
  "COLON",
  "DOUBLE_COLON",
  "INT_TYPE",
  "FLOAT_TYPE",
  "BOOL_TYPE",
  "CHAR_TYPE",
  "VOID_TYPE",
  "IF",
  "ELSE",
  "RETURN",
  "GREATER_THAN",
  "NULL",
  "DATA",
  "CLASS",
  "INSTANCE",
  "FOR",
  "NEW",
  "DOT",
  "ARROW",
  "AMP",
  "INT",
  "FLOAT",
  "ID",
  "TYID",
  "TRUE",
  "FALSE",
  "CHAR"
  };
}

